

//*!!Code automatically generated by 'Arnar and Hakon' !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                          - REMOTE -                                           *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program is made to control the robot via remote control
|*
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*    3)  Point Turns, or turns in place, are achieved by having the motors spin in opposite          *|
|*        directions.                                                                                 *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| REMOTE |+++++++++++++++++++++++++++++++++++++++++++++++//




void Turn()
{
		if(vexRT[Ch1] >= 15)
	{
		while(vexRT[Ch1]>=15)
			{
		motor[leftMotor] = (vexRT[Ch1]/-1)/0.5;
		motor[rightMotor] = vexRT[Ch1] /0.5;
			}
	}

	///turn right
	if(vexRT[Ch1] <= -15)
	{
		while(vexRT[Ch1]<= -15)
			{
		motor[leftMotor] = (vexRT[Ch1]/-1)/0.5;
		motor[rightMotor] = vexRT[Ch1]/0.5;
	    }
  }
}



void Drive ()
{
		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch3];


}


void Claw(){
if(vexRT[Btn6U] == 1)
 {
 motor[clawMotor] = 40;
 }
 else if(vexRT[Btn6D] == 1)
 {
 motor[clawMotor] = -40;
 }
 else
 {
 motor[clawMotor] = 0;
 }
 }


 void Arm(){
if(vexRT[Btn5D] == 1)
 {
 motor[armMotor] = 10;
 }
 else if(vexRT[Btn5U] == 1)
 {
 motor[armMotor] = -40;
 }
 else
 {
 motor[armMotor] = 0;
 }
 }
