#pragma config(Sensor, in1,    rightLineFollower, sensorNone)
#pragma config(Sensor, in2,    centerLineFollower, sensorNone)
#pragma config(Sensor, in3,    leftLineFollower, sensorNone)
#pragma config(Sensor, in6,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  clawSensor,     sensorNone)
#pragma config(Sensor, dgtl6,  buttonSensor,   sensorNone)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorNone)
#pragma config(Sensor, dgtl10, armEncoder,     sensorNone)
#pragma config(Sensor, dgtl11, sonarFront,     sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           armMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "verkefni2.c"
#include "verkefni3.c"
#include "verkefni4.c"

//go_distance();
	//	Drive();
		//Turn();
		//Arm();
		//Claw();

task main()
{	StartTask(drive_around);

	while( vexRT[Btn8D] == 0)
	{//test();
		}
StopAllTasks();




	}




