


//*!!Code automatically generated by 'Arnar and Hakon' !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                          - REMOTE -                                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program is made to control the robot via remote control   																		*|
|*    																																																*|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1) Assign drive motors to joysticks																															*|
|*																																																		*|
|*    2) Assign  arm and claw motor to buttons																												*|
|*																																																		*|
|*    3) Drive around                                                                              		*|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor										*|
|*		Motor Port 5				armMotor						VEX 3-wire module			arm movement motor								*|
|*		Motor Port 6				clawMotor						VEX 3-wire module			claw grip motor										*|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| REMOTE |+++++++++++++++++++++++++++++++++++++++++++++++//


task remote_controller{
	Drive();
	Turn();
	Claw();
	Arm();

}
