

//*!!Code automatically generated by 'Arnar and Hakon' !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                          - REMOTE -                                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program is made to control the robot via remote control   																		*|
|*    																																																*|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1) Assign drive motors to joysticks																															*|
|*																																																		*|
|*    2) Assign  arm and claw motor to buttons																												*|
|*																																																		*|
|*    3) Drive around                                                                              		*|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor										*|
|*		Motor Port 5				armMotor						VEX 3-wire module			arm movement motor								*|
|*		Motor Port 6				clawMotor						VEX 3-wire module			claw grip motor										*|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| REMOTE |+++++++++++++++++++++++++++++++++++++++++++++++//
/*void check_buttons()
{
	}
*/

void Turn()
{
		if(vexRT[Ch1] >= 15)
	{
		while(vexRT[Ch1] >= 15)
			{
		motor[leftMotor] = vexRT[Ch1]/0.5;
		motor[rightMotor] = (vexRT[Ch1]/-1) /0.5;
			}
	}

	///turn right
	if(vexRT[Ch1] <= -15)
	{
		while(vexRT[Ch1]<= -15)
			{
		motor[leftMotor] = (vexRT[Ch1]/-1)/0.5;
		motor[rightMotor] = vexRT[Ch1]/0.5;
	    }
  }
}



void Drive ()
{
		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch3];


}


void Claw(){
if(vexRT[Btn5U] == 1)
 {
 motor[clawMotor] = 40;
 }
else if(vexRT[Btn5D] == 1)
 {
 motor[clawMotor] = -40;
 }
 else
 {
 motor[clawMotor] = 0;
 }
 }


 void Arm(){
if(vexRT[Btn6U] == 1)
 {
 motor[armMotor] = 10;
 }
 else if(vexRT[Btn6D] == 1)
 {
 motor[armMotor] = -40;
 }
 else
 {
 motor[armMotor] = 0;
 }


}
